### ISSUE TITLE
Weather_step not used in rpops

### ISSUE THREAD

**Issue by ChrisJones687** [ncsu-landscape-dynamics/pops-core#96]
should weather_step just use current_index https://github.com/ncsu-landscape-dynamics/pops-core/blob/ff5a96ec7653e93dd3db5e350fd25e55d993e331/include/pops/model.hpp#L73.  It is what we are using in rpops and seems like it is just passed in from r.pops.spread but it looks like it updates in line with step https://github.com/ncsu-landscape-dynamics/r.pops.spread/blob/a322c4ec1793f1218e6dc7f3af5ea6f9279371a7/main.cpp#L1016-L1036.

**Comment by wenzeslaus** [comment]
I hopefully addressed this in #97. The reasons for differences in r.pops.spread are below.

In r.pop.spread, it keeps track of the weather coefficients currently loaded into memory as opposed to weather for all steps. I though this would be eventually handled in schedules, but the loading is really part of the interface, so out of scope for pops-core. Hence, rather than forcing r.pops.spread to load all the weather or do some hack, I let the caller pass just the current weather, i.e., letting the caller to do the indexing (or whatever) themselves.

Confusingly, the r.pops.spread code may look like it is goes with the steps, but it actually goes only with the unresolved ones which is a mechanism to, at the same time, 1) load only subset of weather for the current output/steering time block and 2) load weather once for all parallel runs. Additionally, [with the scheduling change](https://github.com/ncsu-landscape-dynamics/r.pops.spread/commit/a129f63133957bcdd5c8b9c6472cb27a72f8c8f1), we dropped the more intuitive size of the weather coefficient vector and use slightly sub-optimal but easy to get worst-case size of the vector (the overhead is minimal as no data is actually in there).
